workflows:
  android-workflow:
    name: Texturas Android Build
    max_build_duration: 60
    environment:
      android: true
    scripts:
      - name: Check environment
        script: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          echo "ANDROID_HOME=$ANDROID_HOME"
      - name: Assemble Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - build/outputs/**/debug/*.apk
      - build/outputs/**/release/*.apk
    publishing:
      email:
        recipients:
          - phmello98-create@users.noreply.github.com
        notify:
          success: true
          failure: true